apiVersion: v1
kind: Namespace
metadata:
  name: eirene-prod
  labels:
    name: eirene-prod
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: eirene-monitoring
  labels:
    name: eirene-monitoring
